name: eventy_app
description: "Task Manger"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  flutter_svg: ^2.0.9
  vector_graphics: ^1.1.11
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  flutter_gen_runner:
flutter_gen:
  output: lib/core/gen/

  # Optional
  integrations:
    image: true
    flutter_svg: true

flutter:


  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/files/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
